//! The (pattern, text) pairs of git's t3070-wildmatch, as facts: what git's
//! `dowild` answers for each, in the four modes git's own test drives. The
//! answers were computed once by `testing/dowild.zig` and agree with every
//! expectation t3070 states; git checks them in its own suite.

/// What git answers. `invalid` is a malformed bracket git meets while
/// matching; git returns no match there, and sweep refuses the pattern.
pub const Answer = enum { no, yes, invalid };

pub const Row = struct {
    pattern: []const u8,
    text: []const u8,
    /// `wildmatch`, `iwildmatch`, `pathmatch` and `ipathmatch`: with and
    /// without `WM_PATHNAME`, each with and without `WM_CASEFOLD`.
    answers: [4]Answer,
};

pub const rows = [_]Row{
    .{ .pattern = "foo", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "bar", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "", .text = "", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "???", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "??", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "f*", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*f", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*foo*", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*ob*a*r*", .text = "foobar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*ab", .text = "aaaaaaabababab", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo\\*", .text = "foo*", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo\\*bar", .text = "foobar", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "f\\\\oo", .text = "f\\oo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo\\", .text = "foo\\", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*[al]?", .text = "ball", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[ten]", .text = "ten", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "**[!te]", .text = "ten", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**[!ten]", .text = "ten", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "t[a-g]n", .text = "ten", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "t[!a-g]n", .text = "ten", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "t[!a-g]n", .text = "ton", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "t[^a-g]n", .text = "ton", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "a[]]b", .text = "a]b", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "a[]-]b", .text = "a-b", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "a[]-]b", .text = "a]b", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "a[]-]b", .text = "aab", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "a[]a-]b", .text = "aab", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "]", .text = "]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo*bar", .text = "foo/baz/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo**bar", .text = "foo/baz/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo**bar", .text = "foobazbar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/**/bar", .text = "foo/baz/bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/**/**/bar", .text = "foo/baz/bar", .answers = .{ .yes, .yes, .no, .no } },
    .{ .pattern = "foo/**/bar", .text = "foo/b/a/z/bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/**/**/bar", .text = "foo/b/a/z/bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/**/bar", .text = "foo/bar", .answers = .{ .yes, .yes, .no, .no } },
    .{ .pattern = "foo/**/**/bar", .text = "foo/bar", .answers = .{ .yes, .yes, .no, .no } },
    .{ .pattern = "foo?bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo[/]bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo[^a-z]bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "f[^eiu][^eiu][^eiu][^eiu][^eiu]r", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "f[^eiu][^eiu][^eiu][^eiu][^eiu]r", .text = "foo-bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/foo", .text = "foo", .answers = .{ .yes, .yes, .no, .no } },
    .{ .pattern = "**/foo", .text = "XXX/foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/foo", .text = "bar/baz/foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*/foo", .text = "bar/baz/foo", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "**/bar*", .text = "foo/bar/baz", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "**/bar/*", .text = "deep/foo/bar/baz", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/bar/*", .text = "deep/foo/bar/baz/", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "**/bar/**", .text = "deep/foo/bar/baz/", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/bar/*", .text = "deep/foo/bar", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "**/bar/**", .text = "deep/foo/bar/", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/bar**", .text = "foo/bar/baz", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "*/bar/**", .text = "foo/bar/baz/x", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*/bar/**", .text = "deep/foo/bar/baz/x", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "**/bar/*/*", .text = "deep/foo/bar/baz/x", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "a[c-c]st", .text = "acrt", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "a[c-c]rt", .text = "acrt", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[!]-]", .text = "]", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[!]-]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "\\", .text = "", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "\\", .text = "\\", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*/\\", .text = "XXX/\\", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*/\\\\", .text = "XXX/\\", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo", .text = "foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "@foo", .text = "@foo", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "@foo", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "\\[ab]", .text = "[ab]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[]ab]", .text = "[ab]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:]ab]", .text = "[ab]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[::]ab]", .text = "[ab]", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[[:digit]ab]", .text = "[ab]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\[:]ab]", .text = "[ab]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "\\??\\?b", .text = "?a?b", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "\\a\\b\\c", .text = "abc", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "**/t[o]", .text = "foo/bar/baz/to", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:alpha:]][[:digit:]][[:upper:]]", .text = "a1B", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:digit:][:upper:][:space:]]", .text = "a", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[[:digit:][:upper:][:space:]]", .text = "A", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:digit:][:upper:][:space:]]", .text = "1", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:digit:][:upper:][:spaci:]]", .text = "1", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[[:digit:][:upper:][:space:]]", .text = " ", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:digit:][:upper:][:space:]]", .text = ".", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[[:digit:][:punct:][:space:]]", .text = ".", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:xdigit:]]", .text = "5", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:xdigit:]]", .text = "f", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:xdigit:]]", .text = "D", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:alnum:][:alpha:][:blank:][:cntrl:][:digit:][:graph:][:lower:][:print:][:punct:][:space:][:upper:][:xdigit:]]", .text = "_", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[^[:alnum:][:alpha:][:blank:][:cntrl:][:digit:][:lower:][:space:][:upper:][:xdigit:]]", .text = ".", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-c[:digit:]x-z]", .text = "5", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-c[:digit:]x-z]", .text = "b", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-c[:digit:]x-z]", .text = "y", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-c[:digit:]x-z]", .text = "q", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[\\\\-^]", .text = "]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\\\-^]", .text = "[", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[\\-_]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\]]", .text = "]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\]]", .text = "\\]", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[\\]]", .text = "\\", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "a[]b", .text = "ab", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "a[]b", .text = "a[]b", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "ab[", .text = "ab[", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[!", .text = "ab", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[-", .text = "ab", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[-]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-", .text = "-", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[!a-", .text = "-", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[--A]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[--A]", .text = "5", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[ --]", .text = " ", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[ --]", .text = "$", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[ --]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[ --]", .text = "0", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[---]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[------]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-e-n]", .text = "j", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[a-e-n]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[!------]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[]-a]", .text = "[", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[]-a]", .text = "^", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[!]-a]", .text = "^", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[!]-a]", .text = "[", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a^bc]", .text = "^", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-]b]", .text = "-b]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\]", .text = "\\", .answers = .{ .invalid, .invalid, .invalid, .invalid } },
    .{ .pattern = "[\\\\]", .text = "\\", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[!\\\\]", .text = "\\", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[A-\\\\]", .text = "G", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "b*a", .text = "aaabbb", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*ba*", .text = "aabcaa", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[,]", .text = ",", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\\\,]", .text = ",", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\\\,]", .text = "\\", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[,-.]", .text = "-", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[,-.]", .text = "+", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[,-.]", .text = "-.]", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[\\1-\\3]", .text = "2", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\1-\\3]", .text = "3", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[\\1-\\3]", .text = "4", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "[[-\\]]", .text = "\\", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[-\\]]", .text = "[", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[-\\]]", .text = "]", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[-\\]]", .text = "-", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", .text = "-adobe-courier-bold-o-normal--12-120-75-75-m-70-iso8859-1", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", .text = "-adobe-courier-bold-o-normal--12-120-75-75-X-70-iso8859-1", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "-*-*-*-*-*-*-12-*-*-*-m-*-*-*", .text = "-adobe-courier-bold-o-normal--12-120-75-75-/-70-iso8859-1", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "XXX/*/*/*/*/*/*/12/*/*/*/m/*/*/*", .text = "XXX/adobe/courier/bold/o/normal//12/120/75/75/m/70/iso8859/1", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "XXX/*/*/*/*/*/*/12/*/*/*/m/*/*/*", .text = "XXX/adobe/courier/bold/o/normal//12/120/75/75/X/70/iso8859/1", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "**/*a*b*g*n*t", .text = "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txt", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/*a*b*g*n*t", .text = "abcd/abcdefg/abcdefghijk/abcdefghijklmnop.txtz", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*/*/*", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*/*/*", .text = "foo/bar", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "*/*/*", .text = "foo/bba/arr", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*/*/*", .text = "foo/bb/aa/rr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "**/**/**", .text = "foo/bb/aa/rr", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*X*i", .text = "abcXdefXghi", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "*X*i", .text = "ab/cXd/efXg/hi", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "*/*X*/*/*i", .text = "ab/cXd/efXg/hi", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "**/*X*/**/*i", .text = "ab/cXd/efXg/hi", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "fo", .text = "foo", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "foo/bar", .text = "foo/bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/*", .text = "foo/bar", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo/*", .text = "foo/bba/arr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo/**", .text = "foo/bba/arr", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "foo*", .text = "foo/bba/arr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo**", .text = "foo/bba/arr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo/*arr", .text = "foo/bba/arr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo/**arr", .text = "foo/bba/arr", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo/*z", .text = "foo/bba/arr", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "foo/**z", .text = "foo/bba/arr", .answers = .{ .no, .no, .no, .no } },
    .{ .pattern = "foo?bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo[/]bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "foo[^a-z]bar", .text = "foo/bar", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "*Xg*i", .text = "ab/cXd/efXg/hi", .answers = .{ .no, .no, .yes, .yes } },
    .{ .pattern = "[A-Z]", .text = "a", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[A-Z]", .text = "A", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[a-z]", .text = "A", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[a-z]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:upper:]]", .text = "a", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[[:upper:]]", .text = "A", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[[:lower:]]", .text = "A", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[[:lower:]]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[B-Za]", .text = "A", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[B-Za]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[B-a]", .text = "A", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[B-a]", .text = "a", .answers = .{ .yes, .yes, .yes, .yes } },
    .{ .pattern = "[Z-y]", .text = "z", .answers = .{ .no, .yes, .no, .yes } },
    .{ .pattern = "[Z-y]", .text = "Z", .answers = .{ .yes, .yes, .yes, .yes } },
};
