//! `zig run tools/normalize.zig > src/composition.zig`.
const std = @import("std");
const Mapping = struct { code: u21, values: [2]u21, len: usize };
fn expand(maps: []const Mapping, code: u21, out: *std.ArrayList(u21), gpa: std.mem.Allocator) !void {
    for (maps) |m| if (m.code == code) {
        for (m.values[0..m.len]) |v| try expand(maps, v, out, gpa);
        return;
    };
    try out.append(gpa, code);
}
pub fn main(init: std.process.Init) !void {
    const gpa = init.arena.allocator();
    var maps: std.ArrayList(Mapping) = .empty;
    var ccc: std.ArrayList(struct { u21, u8 }) = .empty;
    var excluded: std.AutoHashMap(u21, void) = .init(gpa);
    var lines = std.mem.splitScalar(u8, @embedFile("DerivedNormalizationProps.txt"), '\n');
    while (lines.next()) |line| {
        if (line.len == 0 or line[0] == '#') continue;
        var f = std.mem.splitScalar(u8, line, ';');
        const range = std.mem.trim(u8, f.next().?, " ");
        const prop = std.mem.trim(u8, f.next().?, " ");
        if (!std.mem.startsWith(u8, prop, "Full_Composition_Exclusion")) continue;
        var ends = std.mem.splitSequence(u8, range, "..");
        const first = try std.fmt.parseInt(u21, ends.next().?, 16);
        const last = if (ends.next()) |e| try std.fmt.parseInt(u21, e, 16) else first;
        var cp = first;
        while (cp <= last) : (cp += 1) try excluded.put(cp, {});
    }
    lines = std.mem.splitScalar(u8, @embedFile("UnicodeData.txt"), '\n');
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        var f = std.mem.splitScalar(u8, line, ';');
        const cp = try std.fmt.parseInt(u21, f.next().?, 16);
        _ = f.next();
        _ = f.next();
        const cc = try std.fmt.parseInt(u8, f.next().?, 10);
        if (cc != 0) try ccc.append(gpa, .{ cp, cc });
        _ = f.next();
        const decomp = f.next().?;
        if (decomp.len == 0 or decomp[0] == '<') continue;
        var m: Mapping = .{ .code = cp, .values = @splat(0), .len = 0 };
        var values = std.mem.tokenizeScalar(u8, decomp, ' ');
        while (values.next()) |v| {
            m.values[m.len] = try std.fmt.parseInt(u21, v, 16);
            m.len += 1;
        }
        try maps.append(gpa, m);
    }
    var buf: [4096]u8 = undefined;
    var stdout = std.Io.File.stdout().writerStreaming(init.io, &buf);
    const w = &stdout.interface;
    try w.writeAll("//! Generated by tools/normalize.zig from Unicode 18.0.0 UCD.\n//! Unicode-3.0 license: UNICODE-LICENSE.txt.\npub const Mark = struct { code: u21, class: u8 };\npub const marks = [_]Mark{\n");
    for (ccc.items) |m| try w.print(".{{ .code = 0x{x}, .class = {d} }},\n", .{ m[0], m[1] });
    try w.writeAll("};\npub const Decomposition = struct { code: u21, values: [4]u21, len: u3 };\npub const decompositions = [_]Decomposition{\n");
    for (maps.items) |m| {
        var expanded: std.ArrayList(u21) = .empty;
        try expand(maps.items, m.code, &expanded, gpa);
        std.debug.assert(expanded.items.len <= 4);
        try w.print(".{{ .code = 0x{x}, .values = .{{", .{m.code});
        for (0..4) |i| try w.print("0x{x},", .{if (i < expanded.items.len) expanded.items[i] else 0});
        try w.print("}}, .len = {d} }},\n", .{expanded.items.len});
    }
    try w.writeAll("};\npub const Pair = struct { first: u21, second: u21, result: u21 };\npub const pairs = [_]Pair{\n");
    var pairs: std.ArrayList(struct { u21, u21, u21 }) = .empty;
    for (maps.items) |m| if (m.len == 2 and !excluded.contains(m.code)) {
        try pairs.append(gpa, .{ m.values[0], m.values[1], m.code });
    };
    const Order = struct {
        fn less(_: void, a: @TypeOf(pairs.items[0]), b: @TypeOf(pairs.items[0])) bool {
            return a[0] < b[0] or (a[0] == b[0] and a[1] < b[1]);
        }
    };
    std.mem.sort(@TypeOf(pairs.items[0]), pairs.items, {}, Order.less);
    for (pairs.items) |p| try w.print(".{{ .first = 0x{x}, .second = 0x{x}, .result = 0x{x} }},\n", .{ p[0], p[1], p[2] });
    try w.writeAll("};\n");
    try w.flush();
}
